# Generated by Django 3.1.4 on 2020-12-05 20:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AreaOfWork',
            new_name='Areas',
        ),
    ]
