# Generated by Django 3.1.4 on 2020-12-05 20:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0002_auto_20201205_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Areas',
            new_name='Area',
        ),
    ]
