# Generated by Django 3.1.4 on 2020-12-05 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20201205_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='full_description',
            new_name='description',
        ),
        migrations.RemoveField(
            model_name='project',
            name='author',
        ),
        migrations.RemoveField(
            model_name='project',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='project',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded'),
        ),
    ]
