# Generated by Django 3.1.4 on 2020-12-21 14:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(max_length=128, region=None)),
                ('email', models.EmailField(max_length=254)),
                ('facebook', models.CharField(max_length=50, null=True)),
                ('linkedin', models.CharField(max_length=50, null=True)),
                ('twitter', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('photo', models.ImageField(blank=True, null=True, upload_to='uploaded/users')),
                ('title', models.CharField(max_length=50)),
                ('contact', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='contact.contact')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'Team',
            },
        ),
        migrations.CreateModel(
            name='SiteContact',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('additional', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='additional_contact', to='contact.contact')),
                ('primary', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='primary_contact', to='contact.contact')),
            ],
        ),
    ]
