# Generated by Django 3.1.4 on 2020-12-11 14:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_userprofile'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Person', 'verbose_name_plural': 'Team'},
        ),
    ]
