# Generated by Django 3.1.4 on 2020-12-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0005_auto_20201222_1902'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContact',
        ),
    ]
