# Generated by Django 3.1.4 on 2020-12-05 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded'),
        ),
    ]
