# Generated by Django 3.1.4 on 2020-12-05 22:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('landing', '0002_sitecontent_main_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitecontent',
            name='lang',
            field=models.CharField(choices=[('eng', 'English'), ('ua', 'Ukrainian')], default='eng', max_length=10),
            preserve_default=False,
        ),
    ]
