# Generated by Django 3.1.4 on 2020-12-13 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0004_auto_20201211_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='description_ua',
        ),
        migrations.RemoveField(
            model_name='post',
            name='title_ua',
        ),
    ]
