# Generated by Django 3.1.4 on 2020-12-07 21:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('areas', '0004_auto_20201207_1044'),
        ('projects', '0005_project_area'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='areas.area'),
        ),
    ]
