# Generated by Django 3.1.4 on 2020-12-13 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_auto_20201211_1436'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='description_ua',
        ),
        migrations.RemoveField(
            model_name='project',
            name='title_ua',
        ),
        migrations.AlterField(
            model_name='project',
            name='description',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='title',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
