# Generated by Django 3.1.4 on 2020-12-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20201206_1123'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitecontent',
            name='main_photo',
            field=models.ImageField(blank=True, null=True, upload_to='uploaded/site'),
        ),
    ]
