# Generated by Django 3.1.4 on 2020-12-23 09:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_auto_20201207_1044'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SiteContent',
        ),
    ]
